server:
  port: 8081

logging:
  level:
    ROOT: INFO

spring:
  kafka:
    consumer:
#     bootstrap-servers: localhost:9092
      bootstrap-servers: kafka:9092
      group-id: consumer
      client-id: consumer-service
      auto-offset-reset: earliest
      max-poll-records: 1
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: common
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  data:
    mongodb:
      host: mongodb
#      host: localhost
      port: 27017
      database: employees

consumer:
  topic-name: employee-topic
