version: '3.7'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: dev
#      MONGO_INITDB_ROOT_PASSWORD: dev123
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  consumer-service:
    image: consumer-service:1.0-SNAPSHOT
    container_name: consumer-service
    ports:
      - "8081:8081"
    expose:
      - '8081'
    depends_on:
      - mongodb
      - kafka

  producer-api-service:
    image: producer-api:1.0-SNAPSHOT
    container_name: producer-service
    ports:
      - "8082:8082"
    expose:
      - '8082'
    depends_on:
      - mongodb
      - kafka

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092

    depends_on:
      - zookeeper

volumes:
  mongo:
