server:
  port: 8082
spring:
  kafka:
    producer:
#     bootstrap-servers: localhost:9092
      bootstrap-servers: kafka:9092
      client-id: producer
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

producer:
  topic-name: employee-topic